config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to:'homes#top'
  get 'home/about' => 'homes#about'
  get 'search'=>"searches#search"
  resources :books do
  resources :book_coments, only:[:create,:destroy]
  resource :favorites,only:[:create,:destroy]
end
 resources :users,only: [:show,:index,:edit,:update] do
 resource :relationships,only: [:create,:destroy]
 get 'followings'=>'relationships#followings',as:'followings'
 get 'followers'=>'relationships#followers',as:'followers'
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_coments,dependent: :destroy
	has_many :favorites,dependent: :destroy

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def self.looks(search,word)
		if search=="perfect_match"
			@book=Book.where("title LIKE?","#{word}")
		elsif search=="forward_match"
			@book=Book.where("title LIKE?","#{word}%")
		elsif search=="backword_match"
			@book=Book.where("title LIKE?","%#{word}")
		else search=="partial_match"
			@book=Book.where("title LIKE?","%#{word}%")
		
		end
	end

	def favorited_by?(user)
		favorites.where(user_id:user.id).exists?
	end

end

app/models/book_coment.rb
class BookComent < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books,dependent: :destroy
  has_many :book_coments,dependent: :destroy
  has_many :favorites,dependent: :destroy

  attachment :profile_image, destroy: false

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction,length: {maximum: 50}

  has_many :reverse_of_relationships,class_name:"Relationship",foreign_key: "followed_id",dependent: :destroy
  has_many :followers,through: :reverse_of_relationships,source: :follower
  has_many :relationships,class_name:"Relationship",foreign_key:"follower_id",dependent: :destroy
  has_many :followings,through: :relationships,source: :followed
  


 def self.looks(search,word)
   if search=="perfect_match"
      @user=User.where("name LIKE?","#{word}")
   elsif search=="forward_match"
     @user=User.where("name LIKE?","#{word}%")
   elsif search=="backword_match"
     @user=User.where("name LIKE?","%#{word}")
   else search=="partical_match"
     @user=User.where("name LIKE?","%#{word}%")
     
   end  
 end
     

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except:[:top,:about]
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
  end
end

app/controllers/book_coments_controller.rb
class BookComentsController < ApplicationController
  def create
   @book=Book.find(params[:book_id])
   @coment=BookComent.new(book_coment_params)
   @coment.user_id=current_user.id
   @coment.book_id=@book.id
   @coment.save
  end

  def destroy
  @coment=BookComent.find(params[:id])
  @coment.destroy
  
    
  
  end

private
def book_coment_params
  params.require(:book_coment).permit(:coment)
end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_current_user,only:[:edit]

  def show
    @book = Book.find(params[:id])
    @new_book=Book.new
    @user=@book.user
    @book_coment=BookComent.new
    @book_coments=@book.book_coments
  end

  def index
    @books = Book.all
    @book=Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end
 
def ensure_current_user
   @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to books_path
end
end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book=Book.find(params[:book_id])
    favorite=current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book=Book.find(params[:book_id])
    favorite=current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
   current_user.unfollow(params[:user_id])
   redirect_to request.referer
  end

  def followings
    user=User.find(params[:user_id])
    @users=user.followings
  end

  def followers
    user=User.find(params[:user_id])
    @users=user.followers
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!
  
  def search
    @range=params[:range]
    
    if @range=="User"
      @users=User.looks(params[:search],params[:word])
    else
      @books=Book.looks(params[:search],params[:word])
    end 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update,:edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user),notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_coments_helper.rb
module BookComentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_coments/_coment.html.erb
           <%=form_with(model:[book,book_coment],class:"coment_form",remote: true)do |f|%>
           <%=f.text_area:coment,class:"coment"%></br>
          <%=f.submit "送信する",class:"coment_submit"%>
          <%end%>

app/views/book_coments/_coment_index.html.erb
       <tbody>
         <tr>
     <%book_coments.each do|book_coment|%>
          <td><%=attachment_image_tag(book_coment.user,:profile_image, :fill,100,100,fallback:"no-image-icon.jpg")%><br/>
          <%=book_coment.user.name%></td>
         <td> <%=book_coment.coment%></td>
         <%if current_user.id==book_coment.user.id%>
         <td><%=link_to 'Destroy',book_book_coment_path(book_coment.book,book_coment),method: :delete,remote: true,class:"btn btn-sm btn-danger"%></td>
          <%end%>
       </tr>
        <%end%>
        </tbody>

app/views/book_coments/create.js.erb
$("#coment_index").html("<%=j(render "book_coments/coment_index",{book_coments: @coment.book.book_coments})%>");
$("textarea").val('')

app/views/book_coments/destroy.js.erb
$("#coment_index").html("<%=j(render "book_coments/coment_index",{book_coments: @coment.book.book_coments})%>");

app/views/books/_book_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td id="favorite_btn<%=book.id%>">
           <%=render 'favorites/favorite',book: book%>
        </td>
        <td>コメント数<%=book.book_coments.count%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <%=render 'layouts/errors', obj: @book%>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'book_index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info',user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @new_book %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <td id="favorite_btn<%=@book.id%>">
            <%=render 'favorites/favorite',book: @book%>
            　</td>
          <td>コメント数<%=@book.book_coments.count%></td>
          <%if current_user.id==@user.id%>
          <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
          <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
        <%end%>
         </tr>
         </table>
         <table class="coment">
         <div id="coment_index">
           <%=render "book_coments/coment_index",book_coments: @book_coments%>
           </div>
        </table>
        <tr>
        <td>
          <%=render 'book_coments/coment',book: @book,book_coment: @book_coment%>
          </td>
          </tr>

      </div>
</div>

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>


      <%= link_to book_favorites_path(book.id), method: :delete,remote: true do %>

        <i class="fas fa-heart unlike-btn"><%= book.favorites.count %></i>
      <% end %>



    <% else %>


      <%= link_to book_favorites_path(book.id), method: :post,remote:true do %>
        <i class="fas fa-heart like-btn"><%= book.favorites.count %></i>
      <% end %>



  <% end %>

app/views/favorites/create.js.erb
$('#favorite_btn<%=@book.id%>').html("<%=j(render "favorites/favorite",book: @book) %>");

app/views/favorites/destroy.js.erb
$('#favorite_btn<%= @book.id %>').html("<%= j(render "favorites/favorite", book: @book) %>");

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/relationships/_follow.html.erb
<%if current_user.following?(user)%>

<%=link_to "フォローを外す",user_relationships_path(user.id),method: :delete%>

<%else%>

<%=link_to "フォローする",user_relationships_path(user.id),method: :post%>
<%end%>

app/views/relationships/followers.html.erb
<div class="container">
  <div>
    <h2>Follower Users</h2>
    <% if @users.exists?%>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user|%>
        <tr>
          <td><%=attachment_image_tag(user, :profile_image, :fill,50,50,fallback:"no-image-icon.jpg")%></td>
          <td><%=user.name%></td>
          <td><%=user.followings.count%></td>
          <td><%=user.followers.count%></td>
          <td><%=link_to 'Show',user_path(user)%></td>
        </tr>
         <%end%>
      </tbody>
      </table>
      <%else%>
      <div>
        <p>ユーザーがいません</p>
      </div>
      <%end%>
 　　</div>
　　</div>

app/views/relationships/followings.html.erb
<div class="container">
  <div>
    <h2>Follower Users</h2>
    <% if @users.exists?%>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user|%>
        <tr>
          <td><%=attachment_image_tag(user, :profile_image, :fill,50,50,fallback:"no-image-icon.jpg")%></td>
          <td><%=user.name%></td>
          <td><%=user.followings.count%></td>
          <td><%=user.followers.count%></td>
          <td><%=link_to 'Show',user_path(user)%></td>

        </tr>
        <%end%>
      </tbody>
      </table>
     <table>
      <%else%>
     <td>ユーザーがいません</td>
      <%end%>
 </div>
</div>

app/views/searches/_search.html.erb
<%if user_signed_in?%>
<div class="container">
 <div class="row">
  <div class="mx-auto">
 <%=form_with url: search_path,local: true,method: :get do |f|%>
 <%=f.text_field :word%>
 <%=f.select :range,options_for_select([['User'],['Book']])%>
 <%=f.select :search,options_for_select([["完全一致","perfect_macth"],["前方一致","forward_math"],["後方一致","backword_match"],["部分一致","partial_match"]])%>
 <%=f.submit "検索",class:"btn btn-primary"%>
<%end%>
<%end%>
</div>
</div>
</div>

app/views/searches/search.html.erb
<div class="container px-5 px-sm-0">


      <%if @range=="User"%>
      <h2>User search</h2>
      <table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
  <%else%>
  <h2>Book search</h2>
  <table class="table">
 <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
  <%end%>
</table>


    </div>
  </div>
  </div>
  

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%=link_to(user.followings.count,user_followings_path(user.id))%></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%=link_to(user.followers.count,user_followers_path(user.id))%></th>
    <tr>
      <%if current_user.id!=user.id%>
      <th><%=render 'relationships/follow',user: user%></th>
      <%end%>
      </tr>
  </tr>
</table>

<div class='row'>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>

app/views/users/_user_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数<%=user.followings.count%></td>
        <td>フォロワー数<%=user.followers.count%></td>
        <%if current_user.id!=user.id%>
        <td><%=render 'relationships/follow',user: user%></td>
        <%else%>
        <td></td>
        <%end%>
      
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%=render 'layouts/errors', obj: @book%>
<h2>User info</h2>
<%= render 'info', user: current_user %>
<h2 class="mt-3">New book</h2>
<%= render 'books/form', book: @book %>
</div>
<div class="col-md-8 offset-md-1">
<h2>Users</h2>
<%= render 'user_index',users: @users %>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>